name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 1,15 * *" # This runs the workflow every 1 and 15 of the month at midnight UTC.

jobs:
  aggregate-new-media:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest # Use the appropriate Node.js version here

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable --immutable-cache --check-cache

      - name: Run Your Script
        uses: borales/actions-yarn@v4
        with:
          cmd: aggregate
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: github-action-new-media
          add-paths: |
            src/content/**/*
            video-aggregator/data/output.json
          commit-message: "Github action add new media"
          title: "Github action add new media"
          body: |
            This PR is auto-generated by a GitHub action that runs every day at midnight UTC to add new media.
          reviewers: |
            fcongson
            NoWorries
          delete-branch: true
